language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - cd web
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script:
  - nose2
