language: python
#python:
#  - "3.4"
#  - "3.5"
#  - "3.6"
# command to install dependencies
#os:
#  - linux
#  - osx
matrix:
    include:
        - os: linux
          python: 3.4
          env: TOXENV=py34
        - os: linux
          python: 3.5
          env: TOXENV=py35
        - os: linux
          python: 3.6
          env: TOXENV=py36
        - os: osx
          python: 3.4
          env: TOXENV=py34
        - os: osx
          python: 3.5
          env: TOXENV=py35
        - os: osx
          python: 3.6
          env: TOXENV=py36

install:
  - cd web
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script:
  - nose2 --with-coverage -v

after_success:
  - coveralls