version: '2'

services:
  web:
    build: ./web
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - HOST_ADDR=<insert IP address>
      - FROM_ADDR=<insert your email address>
      - KEY=<insert key>
    volumes:
      - ./web/:/usr/src/app/web
    command: flask run --host=0.0.0.0 --port 8080
