version: '2'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8080"
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - /usr/src/app/web/project/static
      - ./web/:/usr/src/app/web
      - ./papercollection:/home/flask/app/web/papers
    command: /usr/local/bin/gunicorn --enable-stdio-inheritance -w 4 -b :8080 project:app

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - /www/static
    volumes_from:
      - web
    depends_on:
      - web
