version: '2'

services:
  web:
    build: ./web
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - KEY=<insert key>
      - GOOGLE_CLIENT_ID=<insert google client id>
      - GOOGLE_CLIENT_SECRET=<insert secret key>
      - REDIRECT_URI=<insert redirect uri>
      - MAIL_ADDR=<administrators mail address>
      - MAIL_PWD=<administrators password>
    volumes:
      - ./web/:/usr/src/app/web
    command: python run.py --host=0.0.0.0 --port 8080
