version: '2'

services:
  web:
    restart: always
    build: ./web
    environment:
      - KEY=<insert key>
      - GOOGLE_CLIENT_ID=<insert google client id>
      - GOOGLE_CLIENT_SECRET=<insert google client secret>
      - REDIRECT_URI=<insert redirect uri>
    expose:
      - "8080"
    volumes:
      - /usr/src/app/web/project/static
    command: /usr/local/bin/gunicorn -w 2 -b :8080 project:app
    
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - /www/static
    volumes_from:
      - web
    depends_on:
      - web
