version: '2'

services:
  web:
    restart: always
    build: ./web
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - KEY=<insert key>
      - GOOGLE_CLIENT_ID=<insert google client id>
      - GOOGLE_CLIENT_SECRET=<insert google client secret>
      - REDIRECT_URI=<insert redirect uri>
      - MAIL_ADDR=<administrators mail address>
      - MAIL_PWD=<administrators password>
    expose:
      - "8080"
    volumes:
      - /usr/src/app/web/project/static
      - ./web/:/usr/src/app/web
    command: /usr/local/bin/gunicorn -w 2 -b :8080 project:app
    #command: python run.py --host=0.0.0.0 --port 8080

    
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - /www/static
    volumes_from:
      - web
    depends_on:
      - web
